=== ivol84/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="Project" type="ProjectType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Groups">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="Group" type="GroupType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
                <xs:element type="xs:IDREFS" name="groupIds"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="email" use="required"/>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:complexType name="ProjectType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" minOccurs="0" type="xs:string"/>
        </xs:all>
        <xs:attribute type="xs:ID" name="id" use="required"/>
    </xs:complexType>

    <xs:complexType name="GroupType">
        <xs:all>
            <xs:element name="projectId" type="xs:IDREF"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="type" type="GroupStatusType"/>
        </xs:all>
        <xs:attribute type="xs:ID" name="id" use="required"/>
    </xs:complexType>

    <xs:simpleType name="GroupStatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ivol84/masterjava/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Users>
        <User email="gmail@gmail.com" flag="active" city="kiv">
            <fullName>Full Name</fullName>
            <groupIds>masterjava01</groupIds>
        </User>
        <User email="admin@javaops.ru" flag="superuser" city="spb">
            <fullName>Admin</fullName>
            <groupIds>masterjava01</groupIds>
        </User>
        <User email="mail@yandex.ru" flag="deleted" city="spb">
            <fullName>Deleted</fullName>
            <groupIds>masterjava01</groupIds>
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Projects>
        <Project id="masterjava">
            <name>masterjava</name>
            <description>For seniour</description>
        </Project>
    </Projects>
    <Groups>
        <Group id="masterjava01">
            <projectId>masterjava</projectId>
            <name>masterjava01</name>
            <type>CURRENT</type>
        </Group>
    </Groups>
</Payload>
